### ISSUE TITLE
Generalizing GO-off

### ISSUE THREAD

**Issue by MKoesters** [konetom/GO-off#1]
Hi @konetom ,

Thanks for your work!
I found your script while looking for a way to automatize the Gorilla/REVIGO workflow for an mouse dataset.
I decided to restructure your project a little bit to make it linux compatible, to allow choosing different organisms and implemented a CLI. 
I'm also planning to implement some more REVIGO options to set.

I wanted to know if you would accept a PR, in that case I'd also update the docs in the next few days and provide some example on how to use the CLI.
My fork is here https://github.com/MKoesters/GO-off

Best,
Manuel

**Comment by konetom** [comment]
Dear @MKoesters 
Thanks a lot for your interest in this project.
I am very happy to see your enthusiasm in development of my script. I will check out your contribution as soon as possible.

If you would have any question related to the script, don't hesitate and ask me, please.

Honestly, I'm considering myself still as a beginner in programming/scripting, because I'm mostly focused on molecular biology questions rather than pure bioinformatics. However, my priority could possibly change, sooner or later.

Anyways, it will be my pleasure to help you :)

**Comment by MKoesters** [comment]
Okay, I updated the documentation and added some help for the CLI options.
However I removed the file merging part for simplicity on my side.
After I reintroduced this in my fork, I'll do a PR and you can see, if you want to merge it :)

Would it be okay, if I'd enter a CLI option to skip the file merging procedure?

BTW, I actually do the opposite, I'm a biologist by training, however I do almost only bioinformatics since a couple of years.

Best,
Manuel

**Comment by konetom** [comment]
That would be great! Thanks a lot.

**Comment by konetom** [comment]
Nowadays, I am working on implementation of another online tool called PLAZA for plant research (https://bioinformatics.psb.ugent.be/plaza/versions/plaza_v4_dicots/).
But more interestingly, I am planning to incorporate merging of the genes associated with GO categories (made by GO-off) with theirs relative expression (relative expression data will not be provided) or any other dataset comprising fold change values. The result of this merging is used in clustered heatmap. The heatmap is showing, GO categories (y axis) and theirs associated genes (on x axis). If the gene is present in particular GO, it's either red colored (means expression is upregulated) or blue colored (means expression is downregulated).
![picture](https://user-images.githubusercontent.com/34043739/105339115-9bd08980-5bdc-11eb-87af-ee2134f0975f.jpg)
